### ISSUE TITLE
Additional Cognito user attribute

### ISSUE THREAD

**Issue by daaru00** [Botre/amazon-cognito-vuex-module#2]
Hi,

is it possible to use additional CognitoUserAttribute in the [signUp action](https://github.com/Botre/amazon-cognito-vuex-module/blob/master/src/actions.js#L182)?

It would be nice to have something like this:
```javascript
$store.dispatch('signUp', {
  email: 'hello@world.com', 
  password: 'dontforgetme',
  name: 'John' //use name attribute
  custom: {
    company: 'MyCompanyName' //use custom:company attribute
  }
})
```

**Comment by Botre** [comment]
Hello @daaru00 ,

I personally never use custom attributes (I keep those in a dedicated table), but adding this should be trivial. You (or anyone else) are welcome to submit a pull request with this feature 😄

**Comment by Botre** [comment]
Will be refactored in V2 to:

{
  'email': 'example.com',
  'password': 'secret',
  'attributeList': {
     ....
  }
}

**Comment by Botre** [comment]
Released
